Changes record table logic
Yurchenkov/Epic-Sail-URP pull request #27
Opened 2021-09-07 09:45 UTC by MiNiGor

2021-09-08 10:22 UTC, Yurchenkov requested changes

2021-09-08 10:22 UTC, Yurchenkov commented on Assets/Scripts/GameManager.cs
>          playerData = SaveLoadManager.Load<Player>("Player") != null ? (Player)SaveLoadManager.Load<Player>("Player") : playerData;
@MiNiGor тут можно использовать вот такую конструкцию 
SaveLoadManager.Load<Player>("Player") ?? playerData;

так короче и красивее

2021-09-08 10:22 UTC, Yurchenkov commented on Assets/Scripts/Obstacle.cs
> +            RecordTable.AddObstacleCost(2);
@MiNiGor давай вынесем множитель стоимости в константу в Constants и назовём MATCHABLE_OBSTACLE_COST_MULTIPLIER

2021-09-08 10:22 UTC, Yurchenkov commented on Assets/Scripts/Player.cs
> +        if (GameManager.instance.currentLevelType == Constants.LEVEL_TYPE_LINEAR) SetRecord();
@MiNiGor давай Equals использовать. Мы уже обсуждали этот момент

2021-09-08 10:22 UTC, Yurchenkov commented on Assets/Scripts/RecordTable.cs
@MiNiGor лишняя пустая строчка

2021-09-08 19:09 UTC, MiNiGor commented on Assets/Scripts/GameManager.cs
>          playerData = SaveLoadManager.Load<Player>("Player") != null ? (Player)SaveLoadManager.Load<Player>("Player") : playerData;
Так видимо не получится. Система хочет работать с object, а Player не наследуется от object.

2021-09-08 19:11 UTC, MiNiGor commented on Assets/Scripts/Obstacle.cs
> +            RecordTable.AddObstacleCost(2);
Я планировал сделать разные коэффициенты для каждого типа препятствий.

2021-09-10 07:50 UTC, Yurchenkov approved these changes

2021-09-10 07:54 UTC, merged